first_name = input('Enter first name ')
last_name = input('Enter last name ')
print(f"Hello {first_name} {last_name}, I am so very happy to meet you!")
age = input(f"How old are you {first_name}? ")
print(f"{age} years old?  That's a great age {first_name}!")
play_game = input(f"Would you like to play a game {first_name}? ")
